package observatory;

import javax.swing.ImageIcon;
import vroddon.sw.Vocab;

/**
 *
 * @author vroddon
 */
public class DialogVocabulary extends javax.swing.JDialog {

    /** Creates new form DialogVocabulary */
    public DialogVocabulary(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        stName = new javax.swing.JLabel();
        labelSemaforo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        stTitulo.setText("Resource not found");
        stTitulo.setName("stTitulo"); // NOI18N

        jButton1.setText("OK");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        stName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        stName.setText("Vocabulary name");
        stName.setName("stName"); // NOI18N

        labelSemaforo.setIcon(null);
        labelSemaforo.setName("labelSemaforo"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/observatory/resources/url.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                                .addComponent(labelSemaforo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stTitulo)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(stTitulo)))
                    .addComponent(labelSemaforo))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setVocab(Vocab v)
    {
        stTitulo.setText(v.uri);
        stName.setText(v.vocab);
        setSemaforo(v.alive ? 1 : -1);
    }

    /**
     * 1 verde
     * 0 nada
     * -1 rojo
     */
    public void setSemaforo(int valor) {

        ImageIcon ii = null;
        if (valor == 1) {
            ii = new ImageIcon(getClass().getResource("/observatory/resources/semaforoverde32.png"));
        } else if (valor == -1) {
            ii = new ImageIcon(getClass().getResource("/observatory/resources/semafororojo32.png"));
        } else {
            ii = new ImageIcon(getClass().getResource("/observatory/resources/semaforoapagado32.png"));
        }
        if (ii == null) {
            return;
        }
        ii.getImage().flush();
        labelSemaforo.setIcon(ii);
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogVocabulary dialog = new DialogVocabulary(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelSemaforo;
    private javax.swing.JLabel stName;
    private javax.swing.JLabel stTitulo;
    // End of variables declaration//GEN-END:variables

}
